version: '3.8'

services:
  redis:
    container_name: redis
    image: 'redis:latest'
    environment:
      - REDIS_PASSWORD=
    ports:
      - '6379:6379'
    command: ["redis-server", "--requirepass", ""]
    networks:
      - docker_eusurvey-network

networks:
  docker_eusurvey-network:
    external: true
