apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-tomcat-spring-properties-secret
  labels:
    app: {{ include "common.names.fullname" . }}
type: Opaque
data:
  spring.properties: '{{ .Files.Get (printf "config/%s/spring.properties" .Values.environment) | b64enc }}'

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-tomcat-cache-config-secret
  labels:
    app: {{ include "common.names.fullname" . }}
type: Opaque
data:
  ehcache.xml: '{{ .Files.Get (printf "config/%s/ehcache.xml" .Values.environment) | b64enc }}'


