
{{- if and .Values.persistence.surveys.enabled (not .Values.persistence.surveys.existingClaim)  -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "common.names.fullname" . }}-tomcat-surveys
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.surveys.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.surveys.size | quote }}
  {{- include "common.storage.class" (dict "persistence" .Values.persistence.surveys "global" .Values.global) | nindent 2 }}
{{- end -}}
