
global:
  defaultStorageClass: "standard"

tomcat:
  replicaCount: 2 
  service:
    type: ClusterIP
    ports: 
      http: 8080
  image:
    registry: ghcr.io
    repository: circabc/tomcat-eusurvey-server-k8s
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "1Gi"  
      cpu: "500m"     
    limits:
      memory: "2Gi"    
      cpu: "1000m"     
  lifecycleHooks:
    postStart:
      exec:
        command:
          - /bin/sh
          - -c
          - |
            # Move the WAR file if the directory doesn't exist
            if [ ! -d /opt/bitnami/tomcat/webapps/eusurvey ]; then
              mv /usr/local/share/eusurvey.war /opt/bitnami/tomcat/webapps/eusurvey.war;
            fi

            # Redirect eusurvey-error.log to stderr
            if [ ! -L /opt/bitnami/tomcat/logs/eusurvey-error.log ]; then
              ln -sf /dev/stderr /opt/bitnami/tomcat/logs/eusurvey-error.log;
            fi

            # Redirect eusurvey-info.log to stdout
            if [ ! -L /opt/bitnami/tomcat/logs/eusurvey-info.log ]; then
              ln -sf /dev/stdout /opt/bitnami/tomcat/logs/eusurvey-info.log;
            fi

  extraVolumeMounts:
  - name: usr-local-share-volume  
    mountPath: /usr/local/share
  - name: tmp-volume
    mountPath: /eusurveytemp/tmp
  - name: eusurvey-files
    mountPath: /eusurveytemp/files
  - name: eusurvey-surveys
    mountPath: /eusurveytemp/surveys
  - name: eusurvey-users
    mountPath: /eusurveytemp/users
  - name: eusurvey-archive
    mountPath: /eusurveytemp/archive

  extraVolumes:
    - name: usr-local-share-volume  
      emptyDir: {}
    - name: tmp-volume
      emptyDir: {}
    - name: eusurvey-files
      persistentVolumeClaim:
        claimName: eusurvey-files
    - name: eusurvey-surveys
      persistentVolumeClaim:
        claimName: eusurvey-surveys
    - name: eusurvey-users
      persistentVolumeClaim:
        claimName: eusurvey-users
    - name: eusurvey-archive
      persistentVolumeClaim:
        claimName: eusurvey-archive

  initContainers:
    - name: copy-eusurvey-war
      image: ghcr.io/circabc/tomcat-eusurvey-server-k8s:latest
      imagePullPolicy: IfNotPresent 
      command:
        - /bin/sh
        - -c
        - |
          # Move the WAR file if the directory doesn't exist
          if [ ! -d /opt/bitnami/tomcat/webapps/eusurvey ]; then
            mv /opt/bitnami/tomcat/webapps/eusurvey.war /usr/local/share/eusurvey.war;
          fi
  


      volumeMounts:
        - name: usr-local-share-volume  
          mountPath: /usr/local/share

  extraEnvVars:
    - name: JAVA_OPTS
      value: "-Djava.awt.headless=true"  
  hostAliases:
  - ip: "192.168.49.1"
    hostnames:
    - "openldap"
    - "eulogin"

  readinessProbe:
    enabled: false
  customReadinessProbe:
    httpGet:
      path: /eusurvey
      port: 8080
    initialDelaySeconds: 120
    periodSeconds: 5
    failureThreshold: 3

  livenessProbe:
    enabled: false
  customLivenessProbe:
    httpGet:
      path: /eusurvey
      port: 8080
    initialDelaySeconds: 180
    periodSeconds: 10
    failureThreshold: 3
    
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx    
    pathType: ImplementationSpecific  
    ingressClassName: nginx
    extraRules:
    - http:
        paths:
          - path: /eusurvey
            pathType: ImplementationSpecific
            backend:
              service:
                name: eusurvey-tomcat  
                port:
                  number: 8080

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi

mysql:
  auth:
    rootPassword: "password"
  primary:
    extraEnvVars:
      - name: EUSURVEY_MYSQL_DATABASE
        value: eusurveydb
      - name: EUSURVEY_MYSQL_USER
        value: eusurveyuser
      - name: EUSURVEY_MYSQL_PASSWORD
        value: eusurveyuser
      - name: EUSURVEY_MYSQL_ROOT_PASSWORD
        value: password
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi

    configuration: |-
      [mysqld]
      default_authentication_plugin={{- .Values.auth.defaultAuthenticationPlugin | default "mysql_native_password" }}
      skip-name-resolve
      log_bin_trust_function_creators = 1
      explicit_defaults_for_timestamp
      basedir=/opt/bitnami/mysql
      plugin_dir=/opt/bitnami/mysql/lib/plugin
      port={{ .Values.primary.containerPorts.mysql }}
      mysqlx={{ ternary 1 0 .Values.primary.enableMySQLX }}
      mysqlx_port={{ .Values.primary.containerPorts.mysqlx }}
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      datadir=/bitnami/mysql/data
      tmpdir=/opt/bitnami/mysql/tmp
      max_allowed_packet=16M
      bind-address=*
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
      log-error=/opt/bitnami/mysql/logs/mysqld.log
      character-set-server=UTF8
      slow_query_log=0
      long_query_time=10.0
      sql_mode = 'NO_ENGINE_SUBSTITUTION'

      [client]
      port={{ .Values.primary.containerPorts.mysql }}
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      default-character-set=UTF8
      plugin_dir=/opt/bitnami/mysql/lib/plugin

      [manager]
      port={{ .Values.primary.containerPorts.mysql }}
      socket=/opt/bitnami/mysql/tmp/mysql.sock
      pid-file=/opt/bitnami/mysql/tmp/mysqld.pid

  initdbScripts:
    setup.sql: |
      CREATE DATABASE IF NOT EXISTS eusurveydb CHARACTER SET utf8 COLLATE utf8_general_ci;
      CREATE DATABASE IF NOT EXISTS eusurveyreportdb CHARACTER SET utf8 COLLATE utf8_general_ci;
      CREATE USER 'eusurveyuser'@'%' IDENTIFIED BY 'eusurveyuser'; 
      GRANT ALL PRIVILEGES ON eusurveydb.* TO 'eusurveyuser'@'%';
      GRANT EVENT ON *.* TO 'eusurveyuser'@'%';
      CREATE USER 'eusurveyruser'@'%' IDENTIFIED BY 'eusurveyruser'; 
      GRANT ALL PRIVILEGES ON eusurveyreportdb.* TO 'eusurveyruser'@'%';
      SET GLOBAL event_scheduler = ON;
      SET GLOBAL log_bin_trust_function_creators = 1;
      SET GLOBAL TRANSACTION ISOLATION LEVEL READ COMMITTED;
      USE eusurveydb;
      SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
      CREATE TABLE IF NOT EXISTS mv_surveys_numberpublishedanswers (
        SURVEYUID varchar(255) NOT NULL,
        PUBLISHEDANSWERS bigint(21) NOT NULL DEFAULT 0,
        LASTANSWER datetime DEFAULT NULL,
        MW_TIMESTAMP datetime DEFAULT NULL,
        KEY MV_SURVEYS_IND (SURVEYUID,PUBLISHEDANSWERS)
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
      SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;
 


redis: 
  architecture: standalone
  auth: 
    enabled: false
  master:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 2Gi

phpmyadmin:
  enabled: true
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /$2
      nginx.ingress.kubernetes.io/use-regex: "true"
    pathType: ImplementationSpecific  
    ingressClassName: nginx
    extraRules:
    - http:
        paths:
          - path: /phpmyadmin(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: eusurvey-phpmyadmin  
                port:
                  number: 80
  extraEnvVars:
    - name: PMA_ABSOLUTE_URI
      value: "http://10.178.57.74/phpmyadmin/"
  db:
    host: eusurvey-mysql
    port: 3306
    existingSecret: ""
    database: eusurveydb
    username: eusurveyuser
    password: eusurveyuser
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  persistence:
    enabled: false


persistence:
  files:
    enabled: true
    existingClaim: false
    accessModes: ["ReadWriteMany"]
    size: "5Gi"
  surveys:
    enabled: true
    existingClaim: false
    accessModes: ["ReadWriteMany"]
    size: "5Gi"
  users:
    enabled: true
    existingClaim: false
    accessModes: ["ReadWriteMany"]
    size: "5Gi"
  archive:
    enabled: true
    existingClaim: false
    accessModes: ["ReadWriteMany"]
    size: "5Gi"